apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnEvaluationDefinition
metadata:
  name: demoapp-heatlh-check
spec:
  objectives:
    - keptnMetricRef:
        name: demoapp-latency
        namespace: {{ .Release.Namespace }}
      evaluationTarget: "<1" #less than 1s